[platformio]
default_envs = heltec_tx

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  sandeepmistry/LoRa@^0.8.0
  mikalhart/TinyGPSPlus@^1.0
  bblanchon/ArduinoJson@^7.0.0
  knolleary/PubSubClient@^2.8
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor

[env:heltec_tx]
board = heltec_wifi_lora_32
build_src_filter = -<*> +<../boards/heltec/src>
build_flags =
  -D BOARD_HELTEC_V1
  -D LORA_FREQ_HZ=868.1E6
  -D LORA_SF=7
  -D LORA_BW=125E3
  -D LORA_CR=5
  -D LORA_TXPWR=14
  -D LORA_SYNC_WORD=0xA7
  -D DEVICE_HELTEC
board_build.filesystem = spiffs

[env:ttgo_rx]
board = ttgo-lora32-v1
build_src_filter = -<*> +<../boards/ttgo/src>
build_flags =
  -D BOARD_TTGO_LORA32_V1
  -D LORA_FREQ_HZ=868.1E6
  -D LORA_SF=7
  -D LORA_BW=125E3
  -D LORA_CR=5
  -D LORA_SYNC_WORD=0xA7
  -D DEVICE_GATEWAY
board_build.filesystem = spiffs
